
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 12 20:11:37 CEST 2024
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 33;
  public static final int SHOW = 46;
  public static final int CONST = 49;
  public static final int LLCIERRE = 26;
  public static final int CCIERRE = 24;
  public static final int PUNTOYCOMA = 30;
  public static final int PCIERRE = 22;
  public static final int CASE = 42;
  public static final int CAP = 23;
  public static final int GREATER = 12;
  public static final int REPEAT = 36;
  public static final int FOR = 35;
  public static final int LESS = 13;
  public static final int GREQ = 14;
  public static final int SUML = 10;
  public static final int NOT = 20;
  public static final int AND = 18;
  public static final int IGUAL = 28;
  public static final int LLAP = 25;
  public static final int OR = 19;
  public static final int DIV = 8;
  public static final int VALUEFOR = 41;
  public static final int TYPEDEF = 48;
  public static final int IF = 37;
  public static final int AMPERSAND = 31;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int EQUAL = 17;
  public static final int TRUE = 55;
  public static final int NEW = 51;
  public static final int error = 1;
  public static final int DISTINCT = 16;
  public static final int MUL = 7;
  public static final int COMA = 29;
  public static final int IMP = 52;
  public static final int TYPEBOOL = 3;
  public static final int MOD = 9;
  public static final int BREAK = 43;
  public static final int VOID = 4;
  public static final int PRODL = 11;
  public static final int SWITCH = 40;
  public static final int ENT = 54;
  public static final int PAP = 21;
  public static final int FLECHA = 27;
  public static final int ELSE = 38;
  public static final int PUNTO = 32;
  public static final int READ = 47;
  public static final int FILE = 57;
  public static final int IDEN = 53;
  public static final int TYPEINT = 2;
  public static final int WHILE = 34;
  public static final int LIST = 50;
  public static final int DEFAULT = 44;
  public static final int LEQ = 15;
  public static final int SUM = 5;
  public static final int FALSE = 56;
  public static final int STRUCT = 39;
  public static final int SUB = 6;
}

